### ISSUE TITLE
Support em/rem based padding

### ISSUE THREAD

**Issue by ethanresnick** [propublica/column-setter#17]
Often, it's convenient to set the padding in ems/rems, so it relates to the text size rather than the viewport width. Because border-box is assumed throughout this library (I think), allowing the user to provide padding with an ems/rems unit shouldn't effect any width calculations. In fact, I think supporting this would be as simple as returning the value (with its unit) on `colspan(p, ...)` calls, and removing the `unitless()` check in the `bp-validator` function. Is this something you all would be interested in adding?

**Comment by ethanresnick** [comment]
Note: this logic could probably (with a bit more work) be extended for margins too, but idk if that's as useful in practice.

**Comment by robweychert** [comment]
Column Setter includes a padding option for the sake of any poor soul who wants uniform padding in proportion with a flexible grid. Since `colspan()` is expressly designed to be a percentage width generator, I’m reluctant to have it generate values with other units, especially when those values can easily be stored in variables. For uniform em- or rem-based padding, why not just do something like this?:

```
$uniform-padding: 1em;

.example {
  padding: $uniform-padding;
}
```

**Comment by ethanresnick** [comment]
> For uniform em- or rem-based padding, why not just do something like this?:

That'll definitely work. I guess the downside is that then you have two variables, `$pad` and `$uniform-padding`, and a comment to the effect of "ignore $pad; padding is provided through $uniform-padding". Users also have to remember that `colspan(p, ...)` won't work. That doesn't seem like the most elegant outcome.

**Comment by robweychert** [comment]
> I guess the downside is that then you have two variables

Fair point.

Maybe I’m being pedantic, but since `colspan()` is all about container-proportional values, I’m not crazy about the idea of it encompassing other types of proportional values. If I understand the proposed use case correctly, `colspan(p, 2)` and `colspan(p, 5)` would generate identical output (since, if `p` is based on ems/rems/etc, the first and second arguments in the function call don’t actually have anything to do with each other), which seems weird to me.

On the other hand, `colspan(p)` could be made to do what you’re asking, but my brain still gets stuck on the fact that `p` in this case is not proportional to the actual column structure, and isn’t actually “spanning” anything.

I’d be curious to hear other opinions on this.

**Comment by ethanresnick** [comment]
I think we might just be interpreting the meaning of the `colspan` function slightly differently. To me, its output is just "a `width` to use to size something so that it spans to [first argument] size". Accordingly, calling `colspan(2, ....)` is saying "give me a width that'll spans 2 columns on my grid". The second argument is needed to compute that `width`, but (in my interpretation) that's an implementation detail, rather than something inherent to the meaning of `colspan`.

Given that, `colspan(p)` makes total sense to me, and I'd be in favor of having that independent of whether `colspan(p, ...)` is supported. It saves a second variable, and there's also something easy to remember about "always use `colspan()` when you want a grid-related size".

> `colspan(p)`... isn’t actually “spanning” anything.

The output is a size that _spans_ one padding width in the grid, in the same way `colspan(g, 5)` spans one gutter width.

>  If I understand the proposed use case correctly, `colspan(p, 2)` and `colspan(p, 5)` would generate identical output...which seems weird to me.

Yes, the output would be identical. And, thinking about this more, I'm ambivalent about whether this form should be supported. People who start with fixed size padding probably wouldn't use it anyway, because the `colspan(p)` form will be much more convenient than accurately listing the size of the container at different media queries to use `colspan(p, ...)` appropriately. 

So, the real question is, if someone starts with proportional padding and then switches to fixed width padding, should all their old `colspan(p, ...)` calls continue to work? If they do continue to work, that obviously makes the migration easier, but the resulting CSS will also be a little unnecessarily bloated (as now it's outputting the same padding value at different media queries). So, again, I'm ambivalent.

Normally, there'd be an argument to support the `colspan(p, ....)` form to make the abstraction a little less leaky (i.e., users could not need to know/think about what type of padding there is). But, in practice, the user's gonna need to attend to the type of padding no matter what, because the different padding modes have different design implications, even if all their technical differences could be smoothed over.

**Comment by robweychert** [comment]
Okay, let’s give this a whirl! Implementation is a bit more complicated than it first seems: the `bp-validator()` part is simple enough, but `colspan()` and the `$overlay` part of `grid()` will need some nontrivial tweaks (and I’m sure there are some other affected bits that haven’t occurred to me yet).

@ethanresnick I might not be able to get to it for a few days; if you’d like to take a crack at it in the meantime, feel free to submit a pull request.

**Comment by robweychert** [comment]
@ethanresnick Sorry, I forgot you actually did a more thorough pass on this in your fork earlier. I’ll take a closer look at that.

**Comment by robweychert** [comment]
Column Setter 2.0 now supports this!
